spring:
  application:
    name: meomuneum-backend

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

auth:
  token:
    secret: ${AUTH_TOKEN_SECRET}
    access-expiration-seconds: 3600
    refresh-expiration-seconds: 1209600
